FROM  buster-slim

#COPY qemu-arm-static /usr/bin

#WORKDIR /krksrvbuild07_ws/p.las2
#COPY package*.json ./

RUN apt-get update \
    && apt-get -y install \
    build-essential \
    wget \
    git \
    g++ \
    python3 \
    python3-pip \
    nodejs \
    npm \
    clangd \
    fzf \
    neovim 


#COPY . .
#CMD ["npm", "start"]:w
